### ISSUE TITLE
Add basic testing for the piece inference chess logic

### ISSUE THREAD

**Issue by davidmallasen** [davidmallasen/LiveChess2FEN#15]
Given the complexity and possible combinations in the code in `lc2fen/infer_pieces.py`, it would be extremely beneficial to add some basic testing for (some of) the functions in that file. 

To that end, a new `test` directory could be created in the root of the repository to contain the test scripts. Two good python testing options could be [unittest](https://docs.python.org/3/library/unittest.html) or [pytest](https://docs.pytest.org/en/7.3.x/). 

Feel free to leave a comment if you'd like some help/guidance tackling this problem or if you have some additional ideas.

**Comment by David-davidlxl** [comment]
So I should work on this for now, right? You could assign this issue to me
