### ISSUE TITLE
Clarify piece representation in infer_pieces.py

### ISSUE THREAD

**Issue by davidmallasen** [davidmallasen/LiveChess2FEN#17]
The third dimension in https://github.com/davidmallasen/LiveChess2FEN/blob/7693a472885cf9f36617ca31d7c706b40bc92e68/lc2fen/infer_pieces.py#L80
corresponds to the inverse of `__PREDS_DICT`. This could be made clearer.

**Comment by nayan2167** [comment]
I would like to work on this issue

**Comment by davidmallasen** [comment]
Great @nayan2167 ! If you need some help let me know. You can open a pull request referencing this issue when you do it.

**Comment by nayan2167** [comment]
Hi @David-davidlxl I went through infer_pieces.py infer_pieces.py
can you explain a bit more about what exactly Is problem statement?

**Comment by David-davidlxl** [comment]
Hi @nayan2167 I'm not sure what you're asking--are you asking what "infer_pieces.py" does? Or what you need to do with clarifying the piece representation?

**Comment by nayan2167** [comment]
Hi @David-davidlxl   what do I need to do with clarifying the piece representation that's my question

**Comment by David-davidlxl** [comment]
The issue was opened by @davidmallasen but my guess is that he wanted to have more comments in the code related to the interpretation of `tops`

**Comment by nayan2167** [comment]
yes! Exactly what is tops and how it Is related to __preds_dict, that is what I am asking

**Comment by David-davidlxl** [comment]
Lol. If I explained everything here, there'd be no point of you performing the clarification. You should work through the code to understand what exactly it is. Otherwise I'd be happy to take over the issue and open a pull request later

**Comment by nayan2167** [comment]
so I just have to update docstring by explaining about **tops** and update comments

**Comment by davidmallasen** [comment]
Hello @nayan2167 @David-davidlxl . Sorry for the delay in responding. 

Thanks for updating the comments, we can keep that in the pull request! However, my initial idea was to clarify the actual code. Since the third dimension of those variables corresponds to the inverse of the `__PREDS_DICT` dictionary, I believe creating a [reverse dictionary](https://stackoverflow.com/questions/483666/reverse-invert-a-dictionary-mapping) would avoid the use of "magic numbers" in the code. For example, the inverse of `B` would be `0`, the inverse of `N` would be `2`, etc.

Please let me know if you need further help/clarification.
