### ISSUE TITLE
Network validation failed converting from Onnx to TRT model

### ISSUE THREAD

**Issue by phatdq** [davidmallasen/LiveChess2FEN#3]
I wanted to try it out on my Jetson Nano, which has TRT 7.1. So I have to create the TRT model instead of using the one in Releases. When I run onnx2trt to convert:

`./onnx2trt SqueezeNet1p1.onnx -o SqueezeNet1p1.trt`

It asks me to provide an optimization profile:

```
----------------------------------------------------------------
Input filename:   SqueezeNet1p1.onnx
ONNX IR version:  0.0.5
Opset version:    10
Producer name:    keras2onnx
Producer version: 1.6.5
Domain:           onnx
Model version:    0
Doc string:
----------------------------------------------------------------
Parsing model
Building TensorRT engine, FP16 available:1
    Max batch size:     32
    Max workspace size: 1024 MiB
[2021-03-22 22:50:16   ERROR] Network has dynamic or shape inputs, but no optimization profile has been defined.
[2021-03-22 22:50:16   ERROR] Network validation failed.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create object
Aborted (core dumped)
```
Could you please help me with this step?

**Comment by davidmallasen** [comment]
Hello @phatdq,

I'm not sure about that error, I used the previous version of JetPack which had TRT 6 if I'm not mistaken and I didn't get that error. I don't have the Jetson available right now, so I can't test it either.

Googling the "Network has dynamic or shape inputs, but no optimization profile has been defined." error I've seen that it is something "common" (maybe with the newer version of TRT?) and some links to fix it. Maybe you can try it that way. The keras models are also available in the releases section and you can find all of that code in the `cpmodels` directory. If you haven't looked into it, the steps to go from keras->onnx->trt are in the [kerasmodel2onnx.py](https://github.com/davidmallasen/LiveChess2FEN/blob/master/cpmodels/kerasmodel2onxx.py) file.

Please let me know if you succeed in making it work and how you did it. I would also gladly accept a pull request if the code or the instructions needs to be updated or clarified.

David

**Comment by davidmallasen** [comment]
Hello @phatdq . It's been some time but I found that NVIDIA has released a new tool to convert ONNX models to TRT engines. You can find the info about `trtexec` and how to use it [here](https://docs.nvidia.com/deeplearning/tensorrt/quick-start-guide/index.html#convert-onnx-engine). I'm closing this issue with this but feel free to open it again.
