### ISSUE TITLE
Adjust coordinate values slightly for `detect()` function

### ISSUE THREAD

**Issue by David-davidlxl** [davidmallasen/LiveChess2FEN#36]
![image](https://github.com/davidmallasen/LiveChess2FEN/assets/51491203/a5658c6f-dc59-413f-8501-e1c7d257ef01)

Should those `1200`s be changed to `1199`s?

**Comment by David-davidlxl** [comment]
My thinking was that if the image was indeed of size 1200 x 1200, then the maximum index along the height/width dimension would be 1199, so I was thinking that theoretically it'd be more correct to use `1199` instead of `1200` even though `1200` does not seem to produce any errors

**Comment by davidmallasen** [comment]
I've double-checked but I can't seem to find in the code any reason other than my previous comment. Since this is not causing any problems and changing it could cause obscure issues, we can keep it as is unless we find some bug. In any case, good issue, it was worth taking a look just in case 👍🏽
