### ISSUE TITLE
Dependencies requirements 

### ISSUE THREAD

**Issue by wreed87** [davidmallasen/LiveChess2FEN#7]
Could the README file include all the library version for the framework dependencies

**Comment by davidmallasen** [comment]
You should be able to use the latest versions of the libraries in the README. There have been some updates to JetPack since I last worked on this project so I would advise you to try with the latest versions. As far as I remember, there were no hard dependencies on the library versions.

**Comment by davidmallasen** [comment]
Hello @wreed87,
I added more installation instructions in the README and a `requirements.txt` file with the library versions. Hope it helps!
