### ISSUE TITLE
Having trouble with the installation of onnx-tensorrt

### ISSUE THREAD

**Issue by EdgarVivas** [davidmallasen/LiveChess2FEN#8]
I am relatively new to Jetson Nano, and I wanted to install your chess board recognition algorithm. I think I followed the steps pretty well, and in the onnx-tensorrt installation, when I run the make command in the build folder, I get the following error: 

`CMakeFiles/nvonnxparser.dir/build.make:221: *** target pattern contains no '%'. Stop.
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/nvonnxparser.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

I do not know how to solve this issue. Can someone help me with this? Any type of help will be appreciated.

(Alternatively, for the setup part, do I need to download all 27 assets in the initial release link?)

Thank you.

**Comment by davidmallasen** [comment]
Hello @EdgarVivas ,

I cannot replicate the error so I'm not sure what's going on. Could you try to update CMake as mentioned in the [Troubleshooting](https://github.com/davidmallasen/LiveChess2FEN#troubleshooting)? Maybe the requirements have changed slightly in the onnx-tensorrt project. If you manage to solve this, please let me know here so we can update the README.

For the setup part, you do not need to download all 27 assets. Depending on what you want to do you will need the ChessPiecesDataset and/or the TestImages and at least one of the pretrained models. The `.h5` work with Keras, the `.onnx` with ONNXRuntime and the `.trt` with TensorRT.

Best,
David

**Comment by davidmallasen** [comment]
Hello @EdgarVivas . It's been some time but I found that NVIDIA has released a new tool to convert ONNX models to TRT engines, so you wouldn't need `onnx-tensorrt`. You can find the info about `trtexec` and how to use it [here](https://docs.nvidia.com/deeplearning/tensorrt/quick-start-guide/index.html#convert-onnx-engine). I'm closing this issue with this but feel free to open it again.
